"""Mapping of predicted diseases to standard over-the-counter (OTC) medicines or remedies."""

DISEASE_MEDICINE_MAP = {
    "Common Cold": ["Paracetamol", "Antihistamine (e.g. Cetirizine)", "Decongestant", "Vitamin C"],
    "Influenza": ["Paracetamol", "Ibuprofen", "Plenty of Fluids", "Bed Rest"],
    "COVID-19": ["Paracetamol", "Hydration", "Rest", "Consult Doctor for Antivirals"],
    "Pneumonia": ["Paracetamol for Fever", "Cough Suppressants", "Seek immediate medical attention for antibiotics"],
    "Bronchitis": ["Cough Expectorant", "Ibuprofen", "Humidifier Therapy"],
    "Asthma": ["Use Prescribed Inhaler (Albuterol)", "Avoid Triggers", "Seek emergency care if severe"],
    "Tuberculosis": ["Requires long-term Prescription Antibiotics", "Seek immediate medical attention"],
    "Allergic Rhinitis": ["Antihistamines (Loratadine)", "Nasal Corticosteroids", "Avoid Allergens"],
    "Sinusitis": ["Nasal Decongestant Spray", "Ibuprofen", "Warm Compresses"],
    "Migraine": ["Ibuprofen", "Sumatriptan (if prescribed)", "Rest in a dark room"],
    "Tension Headache": ["Aspirin", "Ibuprofen", "Paracetamol", "Stress Relief Techniques"],
    "Hypertension": ["Consult Doctor for Blood Pressure Medication", "Low-Sodium Diet"],
    "Diabetes Type 2": ["Consult Doctor for Insulin/Metformin", "Dietary Management", "Regular Exercise"],
    "Hyperthyroidism": ["Consult Endocrinologist for Antithyroid Meds", "Beta Blockers (if prescribed)"],
    "Hypothyroidism": ["Levothyroxine (Prescription only)"],
    "Anemia": ["Iron Supplements", "Vitamin B12", "Folic Acid", "Iron-rich Diet"],
    "Gastroenteritis": ["Oral Rehydration Salts (ORS)", "Loperamide (if advised)", "Bland Diet"],
    "Gastritis": ["Antacids", "Proton Pump Inhibitors (Omeprazole)", "Avoid Spicy Foods"],
    "GERD": ["Antacids", "H2 Blockers (Famotidine)", "Eat smaller meals"],
    "Peptic Ulcer": ["Omeprazole", "Antibiotics (if H. pylori) - Consult Doctor"],
    "Appendicitis": ["MEDICAL EMERGENCY. Do not take pain killers. Go to Hospital immediately."],
    "Urinary Tract Infection": ["Over-the-counter pain relievers for cramps", "Cranberry Juice", "Consult Doctor for Antibiotics"],
    "Kidney Stones": ["Ibuprofen", "Drink Excess Water", "Tamsulosin (Prescription)"],
    "Arthritis": ["NSAIDs (Ibuprofen, Naproxen)", "Acetaminophen", "Topical Analgesics"],
    "Osteoporosis": ["Calcium Supplements", "Vitamin D3", "Bisphosphonates (Prescription)"],
    "Dengue Fever": ["Paracetamol", "Hydration (ORS)", "WARNING: Avoid Aspirin & Ibuprofen!"],
    "Malaria": ["Prescription Antimalarials (Artemisinin-based)", "Paracetamol for Fever"],
    "Typhoid": ["Prescription Antibiotics (e.g. Ciprofloxacin)", "Hydration"],
    "Chickenpox": ["Calamine Lotion", "Paracetamol for fever", "Antihistamines for itching"],
    "Measles": ["Paracetamol", "Vitamin A", "Hydration"],
    "Hepatitis B": ["Rest", "Nutritional Support", "Antiviral Medications (if chronic)"],
    "Psoriasis": ["Topical Corticosteroids", "Moisturizers", "Salicylic Acid"],
    "Eczema": ["Hydrocortisone Cream", "Thick Moisturizers", "Antihistamines"],
    "Conjunctivitis": ["Artificial Tears", "Cool Compresses", "Antibiotic Eye Drops (if bacterial)"],
    "Depression": ["Consult Psychiatrist for Antidepressants (SSRI)", "Therapy/Counseling"],
    "Anxiety Disorder": ["Therapy (CBT)", "Consult Doctor for Anxiolytics"],
    "Insomnia": ["Melatonin Supplements", "Sleep Hygiene Practices", "Valerian Root"],
    "Iron Deficiency": ["Ferrous Sulfate (Iron Supplements)", "Vitamin C (to boost absorption)"],
    "Vitamin D Deficiency": ["Vitamin D3 Supplements (Cholecalciferol)", "Sun Exposure"],
    "Food Poisoning": ["Oral Rehydration Salts", "Rest", "Bland Diet (BRAT diet)"]
}
